### ISSUE TITLE
打开报错诶, 

### ISSUE THREAD

**Issue by zynote** [gongxufan/adminlte-plus#1]
<img width="1277" alt="WechatIMG321" src="https://user-images.githubusercontent.com/10859954/55308914-b3320600-548e-11e9-9690-c0b7413959da.png">

**Comment by gongxufan** [comment]
直接双击打开不行，放tomcat或者导入到idea右键打开index.html

看在线的效果：[https://gongxufan.github.io/adminlte-plus/index.html](url)

**Comment by qinyunhu** [comment]
@zynote 目录命名的问题
